### ISSUE TITLE
[BUG] New version of attrs got an mypy checking error

### ISSUE THREAD

**Issue by shenxiangzhuang** [Toloka/crowd-kit#115]
### Observed behavior

Got mypy error in #114 ci execution:

```
crowdkit/aggregation/utils.py:194: error: Returning Any from function declared to return "Series[Any]"  [no-any-return]
Found 1 error in 1 file (checked 79 source files)
```

The error is caused by the new version of [attrs](https://github.com/python-attrs/attrs/releases/tag/24.1.0).

We can reproduce the error by using the newest `24.1.0` version of attrs, and it's ok in old attrs version(`23.2.0`)

### Python Version

3.8

### Crowd-Kit Version

1.3.0.post0

### Other Packages Versions

attrs==24.1.0

**Comment by shenxiangzhuang** [comment]
I found the ci still fail after merged this pr into main: https://github.com/Toloka/crowd-kit/actions/runs/10292704472

Is cache in github action the reason?

**Comment by dustalov** [comment]
I noticed that the problem was caused by the NumPy version 2.0 which was unavailable for Python 3.8 and older versions. I will exclude the impacted checks from CI.

**Comment by dustalov** [comment]
Please try again against the newer revision of `main`.

**Comment by shenxiangzhuang** [comment]
Thanks, I'll try it, .
